version: '3.1'

services:
  permit:
    build: .
    image: crusttech/permit:latest
    volumes:
      - ./storage:/storage
    restart: on-failure
    env_file:
      - .env
    environment:
      VIRTUAL_HOST:     ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
    hostname: ${HOSTNAME}
    networks:
      - party

networks:
  party:
    external: true
